backend:
  name: git-gateway
  # name: test-repo
  branch: main

local_backend: true
logo_url: https://roblindsey.com/assets/images/icons/site-icon.png

media_folder: "src/assets/images/notes/2025"
public_folder: "/assets/images/notes/2025"

collections:
  - name: "notes"
    label: "Note"
    identifier_field: body
    folder: "src/content/notes/2025"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "{{now}}",
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          picker_utc: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
