backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images/notes/2025"
public_folder: "/assets/images/notes/2025"

collections:
  - name: "notes"
    label: "Note"
    identifier_field: permalink
    folder: "src/content/notes/2025"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - {
          label: "Permalink",
          name: "permalink",
          widget: "hidden",
          default: "/notes/2025/{{slug}}/index.html",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
